name: vercel production deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    tags:
      - "alpha-*"

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install vercel cli
        run: npm install --global vercel@latest
      - name: build vercel project
        run: npm run build
      - name: deploy to vercel production
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
